name: netcoresync_moor_generator
description: The code generation tool (as `dev_dependencies`) for `netcoresync_moor` package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.0.2 # https://pub.dev/packages/source_gen
  build_config: ^1.0.0 # https://pub.dev/packages/build_config
  glob: ^2.0.1 # https://pub.dev/packages/glob
  moor: ^4.3.2 # https://pub.dev/packages/moor
  netcoresync_moor:
    path: ../netcoresync_moor

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6 # https://pub.dev/packages/build_runner

