name: netcoresync_client_flutter
description: Dart / Flutter Client for NETCoreSync - a data synchronization library / server component implemented using .NET Core.
version: 0.0.1
homepage: https://github.com/aldycool/NETCoreSync
repository: https://github.com/aldycool/NETCoreSync

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
