name: netcoresync_moor
description: Dart / Flutter Client (opinionated to Moor) for NETCoreSync (a data synchronization library / server component implemented using .NET Core).
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0 # https://pub.dev/packages/meta # ...Because every version of flutter_test from sdk depends on meta 1.3.0...
  moor: ^4.4.1 # https://pub.dev/packages/moor
  uuid: ^3.0.4 # https://pub.dev/packages/uuid

dev_dependencies:
  flutter_test:
    sdk: flutter
  